name: Deploy Math-LLM to GitHub Pages (Unified)

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for actions/checkout and pushing to gh-pages
  pages: write     # Required for actions/configure-pages
  id-token: write  # Required for authentication
  deployments: write  # Required for deployments

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment: production  # Use the environment with API keys
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: List current directory contents
      run: ls -la
    
    - name: Update package-lock.json
      run: npm install
      
    - name: Create demo build (skip tests)
      run: |
        echo "Skipping tests and building demo directly"
        npm run build:skip-tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SKIP_TESTS: 'true'
        GITHUB_ACTIONS: 'true'
    
    - name: Verify build
      run: |
        echo "Contents of dist directory:"
        ls -la dist/
        if [ -f "dist/index.html" ]; then
          echo "✓ index.html exists"
        else
          echo "✗ index.html is missing!"
          exit 1
        fi
        
        echo "Environment variables used for the build:"
        echo "- SKIP_TESTS: $SKIP_TESTS"
        echo "- GITHUB_ACTIONS: $GITHUB_ACTIONS"
        echo "- GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
    
    - name: Add .nojekyll file and copy HTML files
      run: |
        touch ./dist/.nojekyll
        echo "Created .nojekyll file to prevent Jekyll processing"
        cp index.html ./dist/
        cp 404.html ./dist/
        echo "Copied root index.html and 404.html to dist directory"
        ls -la ./dist/
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      with:
        # Specify deployment source branch
        source_dir: ./dist
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true  # Create a new orphan branch for the deployment
        disable_nojekyll: false  # Ensure .nojekyll file is kept
    
    - name: Output deployment URL
      run: |
        echo "Deployed to: https://$(echo $GITHUB_REPOSITORY | cut -d'/' -f1).github.io/Math-LLM/"
        echo "If you see a 404 error, please check that:"
        echo "1. The repository settings have GitHub Pages enabled"
        echo "2. The deployment branch (gh-pages) exists and contains the correct files"