name: Deploy Math-LLM to GitHub Pages

on:
  workflow_dispatch:  # Allows manual triggering only
  
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment: production  # Use the environment you created
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create demo build (skip tests)
      run: |
        echo "Skipping tests and building demo directly"
        npm run build:skip-tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SKIP_TESTS: 'true'
        
    - name: Verify build
      run: |
        echo "Contents of dist directory:"
        ls -la dist/
        if [ -f "dist/index.html" ]; then
          echo "✓ index.html exists"
        else
          echo "✗ index.html is missing!"
          exit 1
        fi
    
    - name: Add .nojekyll file
      run: |
        touch ./dist/.nojekyll
        echo "Created .nojekyll file to prevent Jekyll processing"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true  # Create a new orphan branch for the deployment