name: Deploy Math-LLM to GitHub Pages

on:
  workflow_dispatch:  # Allows manual triggering only
  
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment: production  # Use the environment you created
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create demo build
      run: |
        # Skip tests and just build the demo directly
        npx webpack --mode production --config webpack.demo.config.js
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true  # Create a new orphan branch for the deployment