name: Simplest GitHub Pages Deployment

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  deploy-simple-page:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create simple index.html
      run: |
        mkdir -p gh-pages
        cat > gh-pages/index.html << 'EOL'
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Math-LLM</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
    .container { max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #333; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Math-LLM is working!</h1>
    <p>This is a simple static HTML page to verify GitHub Pages deployment is working correctly.</p>
    <p>The GitHub Pages site is now configured properly.</p>
    <p>You can now run the full deployment workflow.</p>
  </div>
</body>
</html>
EOL
        echo "" > gh-pages/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: gh-pages
        branch: gh-pages
        clean: true